# Generated by Django 5.2 on 2025-08-09 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statu', models.CharField(choices=[('preselectioner', 'Preselectioner'), ('selectioner', 'Selectioner'), ('none', 'En Cours')], default='none', max_length=15)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=10)),
                ('date_postulation', models.DateField()),
                ('cv', models.FileField(upload_to='candidatures/')),
                ('noteCV', models.IntegerField(default=0, null=True)),
                ('noteEntretien', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100)),
                ('statu', models.CharField(choices=[('publier', 'Publier'), ('nonpublier', 'Nonpublier')], default='nonpublier', max_length=15)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('titre_poste', models.CharField(max_length=50)),
                ('departement', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=50)),
                ('contrat', models.CharField(max_length=10)),
                ('date_fin_postulation', models.DateField()),
                ('missions', models.TextField()),
                ('objectifs', models.TextField()),
                ('competences_techniques', models.TextField()),
                ('competences_transversales', models.TextField()),
                ('formation', models.TextField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='fiche_poste/')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255, unique=True)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True)),
                ('statu', models.CharField(choices=[('scheduled', 'Programmé'), ('done', 'Terminé')], default='scheduled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='Recrutement.candidature')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidature',
            name='fiche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recrutement.ficheposte'),
        ),
    ]
