# Generated by Django 5.2 on 2025-05-17 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100)),
                ('statu', models.CharField(choices=[('publier', 'Publier'), ('nonpublier', 'Nonpublier')], default='nonpublier', max_length=15)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('titre_poste', models.CharField(max_length=50)),
                ('departement', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=50)),
                ('contrat', models.CharField(max_length=10)),
                ('date_fin_postulation', models.DateField()),
                ('missions', models.TextField()),
                ('objectifs', models.TextField()),
                ('competences_techniques', models.TextField()),
                ('competences_transversales', models.TextField()),
                ('formation', models.TextField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='fiche_poste/')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statu', models.CharField(choices=[('preselectioner', 'Preselectioner'), ('selectioner', 'Selectioner'), ('none', 'None')], default='none', max_length=15)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=10)),
                ('date_postulation', models.DateField()),
                ('cv', models.FileField(upload_to='candidatures/')),
                ('noteCV', models.IntegerField(default=0, null=True)),
                ('noteEntretien', models.IntegerField(default=0, null=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recrutement.ficheposte')),
            ],
        ),
    ]
