# Generated by Django 5.2 on 2025-08-12 19:30

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='candidatures/'),
        ),
        migrations.AlterField(
            model_name='ficheposte',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='fiche_poste/'),
        ),
    ]
